### ISSUE TITLE
Haml導入

### ISSUE THREAD

**Issue by tanaka-hiroki1989** [tanaka-hiroki1989/plamo-guide#6]
### 背景
viewのコーディングにおいて、より簡潔な記法が求められる。
### 対応
代表的なテンプレートエンジンHamlを採用することにより、HTMLをより抽象的かつ簡潔に書くことができるようにする。
### 作業手順
1. Gemfileに`gem 'haml-rails'`を記述
2. コマンドライン上で`bundle install`を実行

**Comment by tanaka-hiroki1989** [comment]
#3 に統合して、このissueはクローズします。

**Comment by jimako1989** [comment]
:ok:
